---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started

    - name: Pull Image
      shell: docker pull srinivasan2404/calculator:latest

# Hello World
    - name: Run the container
      shell: docker create -it --name Calculator srinivasan2404/calculator
